import { useState, useEffect, useCallback, useRef } from 'react';
import type { FeatureNode } from '../types/feature';
import { useTaskStore } from '../store/taskStore';
import { tr, type Language } from '../i18n';

interface Props {
  projectPath: string | null;
  onSelectFeature: (node: FeatureNode | null) => void;
  selectedId: string | null;
  onFeaturesLoaded: (features: FeatureNode[]) => void;
  language: Language;
}

const COL = {
  surfaceVariant: '#282a2d',
  onSurface: '#e3e2e6',
  onSurfaceVariant: '#c4c7c5',
  outline: '#444746',
  primary: '#8ab4f8',
  yellow: '#d29922',
  green: '#3fb950',
  muted: '#484f58',
};

// ── Inline SVG icons (12x12 viewBox, stroke currentColor) ──
const ICONS = {
  spark:   <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 2l1.5 6.5L20 9l-6.5 1.5L13 17l-1-6.5L5.5 9l6.5-1.5L13 2h-1z"/><circle cx="12" cy="19" r="1.5" fill="currentColor" stroke="none"/></svg>,
  folder:  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z"/></svg>,
  search:  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="8"/><path d="M21 21l-4.35-4.35"/></svg>,
  code:    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>,
  brain:   <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 4a3 3 0 00-3-3 2 2 0 00-2 2v1a2 2 0 002 2h6a2 2 0 002-2V3a2 2 0 00-2-2 3 3 0 00-3 3z"/><path d="M9 20a3 3 0 01-6 0v-2a4 4 0 014-4h2"/><path d="M15 20a3 3 0 006 0v-2a4 4 0 00-4-4h-2"/><line x1="9" y1="14" x2="15" y2="14"/></svg>,
  save:    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg>,
};

// ── Progress phase definitions ──
interface PhaseDef {
  id: string;
  icon: keyof typeof ICONS;
  labelZh: string;
  labelEn: string;
}
const PHASES: PhaseDef[] = [
  { id: 'start', icon: 'spark', labelZh: '初始化分析引擎', labelEn: 'Init analysis engine' },
  { id: 'tree', icon: 'folder', labelZh: '扫描项目文件结构', labelEn: 'Scanning project files' },
  { id: 'discover', icon: 'search', labelZh: 'AI 探索项目架构', labelEn: 'AI exploring architecture' },
  { id: 'tool', icon: 'code', labelZh: '读取关键代码文件', labelEn: 'Reading key source files' },
  { id: 'analyze', icon: 'brain', labelZh: 'AI 分析功能边界', labelEn: 'AI analyzing boundaries' },
  { id: 'save', icon: 'save', labelZh: '构建思维导图', labelEn: 'Building feature map' },
];

export default function FeatureList({ projectPath, onSelectFeature, selectedId, onFeaturesLoaded, language }: Props) {
  const [features, setFeatures] = useState<FeatureNode[]>([]);
  const [loading, setLoading] = useState(false);
  const [progressLabel, setProgressLabel] = useState('');
  const [activePhase, setActivePhase] = useState<string | null>(null);
  const [completedPhases, setCompletedPhases] = useState<Set<string>>(new Set());
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  const autoGenerated = useRef<string | null>(null);

  // Reset on project change
  useEffect(() => { autoGenerated.current = null; }, [projectPath]);

  const loadFeatures = useCallback(async () => {
    if (!projectPath) return;
    try {
      const res = await fetch(`/api/v1/features?project_path=${encodeURIComponent(projectPath)}`);
      const data = await res.json();
      const list = data.features || [];
      setFeatures(list);
      onFeaturesLoaded(list);
      // Auto-generate only if DB is empty for this project
      if (list.length === 0 && projectPath !== autoGenerated.current) {
        autoGenerated.current = projectPath;
        handleGenerate();
      }
    } catch { /* */ }
  }, [projectPath, onFeaturesLoaded]);

  useEffect(() => { loadFeatures(); }, [loadFeatures]);


  const handleGenerate = async () => {
    if (!projectPath) return;
    setLoading(true);
    setProgressLabel('');
    setActivePhase(null);
    setCompletedPhases(new Set());
    const taskId = `analyze_all_${Date.now()}`;
    const isRefresh = features.length > 0;
    useTaskStore.getState().addTask({ id: taskId, type: 'analyze', label: language === 'zh' ? '分析项目地图' : 'Analyze project features', status: 'running', startedAt: Date.now(), detail: tr(language, 'readingCode') });

    // Phase order for progress tracking
    const PHASE_ORDER = ['start', 'tree', 'discover', 'tool', 'analyze', 'save'];
    const markPhaseComplete = (step: string) => {
      setCompletedPhases(prev => {
        const next = new Set(prev);
        const idx = PHASE_ORDER.indexOf(step);
        if (idx >= 0) {
          for (let i = 0; i <= idx; i++) next.add(PHASE_ORDER[i]);
        }
        next.add(step);
        return next;
      });
    };

    try {
      // Use incremental refresh when features already exist, full analysis otherwise
      const endpoint = isRefresh
        ? '/api/v1/features/incremental-refresh'
        : `/api/v1/features/analyze-all/stream?${new URLSearchParams({ project_path: projectPath, language })}`;
      const res = isRefresh
        ? await fetch(endpoint, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ project_path: projectPath, language }),
          })
        : await fetch(endpoint);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);

      const reader = res.body?.getReader();
      if (!reader) throw new Error('No response body');
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });

        const parts = buffer.split('\n\n');
        buffer = parts.pop() || '';

        for (const part of parts) {
          if (!part.trim()) continue;
          const lines = part.split('\n');
          let eventType = '';
          let eventData = '';
          for (const line of lines) {
            if (line.startsWith('event: ')) eventType = line.slice(7).trim();
            else if (line.startsWith('data: ')) eventData = line.slice(6);
          }
          if (!eventType || !eventData) continue;

          try {
            const data = JSON.parse(eventData);
            if (eventType === 'progress') {
              const step = data.step || 'tool';
              setProgressLabel(data.label || '');
              setActivePhase(step);
              // Mark high-level phases complete when they first appear; tool is a sub-phase of discover/analyze
              if (step !== 'tool') markPhaseComplete(step);
              useTaskStore.getState().updateTask(taskId, { detail: data.label });
            } else if (eventType === 'done') {
              // Mark ALL phases complete
              PHASE_ORDER.forEach(p => markPhaseComplete(p));
              setActivePhase(null);
              if (data.features?.length) {
                onSelectFeature(null);
                setFeatures(data.features);
                onFeaturesLoaded(data.features);
                const stats = data.stats || {};
                useTaskStore.getState().updateTask(taskId, {
                  status: 'done',
                  detail: `${stats.groups || 0} groups, ${stats.features || 0} features`
                });
              } else {
                useTaskStore.getState().updateTask(taskId, { status: 'error', detail: tr(language, 'noFeatures') });
              }
            } else if (eventType === 'error') {
              useTaskStore.getState().updateTask(taskId, { status: 'error', detail: data.message || 'Failed' });
            }
          } catch (err) {
            console.warn('[FeatureList] parse error:', err, 'part:', part.substring(0, 200));
          }
        }
      }
    } catch (e: any) {
      if (e.name !== 'AbortError') {
        useTaskStore.getState().updateTask(taskId, { status: 'error', detail: e.message || 'Failed' });
      }
    }
    setLoading(false);
    setProgressLabel('');
    setActivePhase(null);
    setTimeout(() => useTaskStore.getState().removeTask(taskId), 3000);
  };

  return (
    <div className="flex flex-col h-full" style={{ background: COL.surfaceVariant }}>
      <div className="flex items-center justify-between px-3 py-1.5 border-b shrink-0" style={{ borderColor: COL.outline }}>
        <span className="text-caption font-medium uppercase tracking-wide" style={{ color: COL.onSurfaceVariant }}>
          {tr(language, 'features')}
        </span>
        <div className="flex items-center gap-1.5">
          <button
            onClick={handleGenerate}
            disabled={(!features.length && loading) || !projectPath}
            className="text-[9px] p-1 rounded-full transition-colors hover:opacity-80 disabled:opacity-30"
            style={{ background: '#003a75', color: COL.primary }}
            title={features.length > 0 ? tr(language, 'refresh') : tr(language, 'analyze')}>
            {features.length > 0 ? (
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"
                className={loading ? 'animate-spin' : ''}>
                <path d="M1 4v6h6M23 20v-6h-6" /><path d="M20.49 9A9 9 0 0 0 5.64 5.64L1 10m22 4l-4.64 4.36A9 9 0 0 1 3.51 15" />
              </svg>
            ) : (
              loading ? '...' : tr(language, 'analyze')
            )}
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto">
        {/* Progress steps — visible during analysis */}
        {loading && (
          <div className="px-3 py-2.5 border-b space-y-1" style={{ borderColor: COL.outline, background: '#1d2024' }}>
            {/* Phase steps */}
            {PHASES.map((phase) => {
              const isComplete = completedPhases.has(phase.id);
              const isActive = activePhase === phase.id;
              const label = language === 'zh' ? phase.labelZh : phase.labelEn;
              return (
                <div key={phase.id} className="flex items-center gap-2 transition-all duration-300"
                  style={{ opacity: isComplete || isActive ? 1 : 0.3 }}>
                  {/* Status icon */}
                  <span className="shrink-0 flex items-center justify-center w-3.5 h-3.5">
                    {isComplete ? (
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={COL.green} strokeWidth="2.5">
                        <path d="M5 13l4 4L19 7" />
                      </svg>
                    ) : isActive ? (
                      <span className="w-2 h-2 rounded-full animate-pulse-dot" style={{ background: COL.primary }} />
                    ) : (
                      <span className="w-1.5 h-1.5 rounded-full" style={{ background: COL.muted }} />
                    )}
                  </span>
                  {/* Phase icon */}
                  <span style={{ color: isActive ? COL.primary : isComplete ? COL.green : COL.muted, opacity: 0.7 }}>
                    {ICONS[phase.icon]}
                  </span>
                  {/* Label */}
                  <span className="text-caption truncate transition-colors duration-300"
                    style={{ color: isActive ? COL.primary : isComplete ? '#8b949e' : COL.muted }}>
                    {label}
                  </span>
                  {/* Active spinner */}
                  {isActive && (
                    <span className="ml-auto shrink-0 flex gap-0.5">
                      <span className="w-0.5 h-3 rounded-full animate-pulse" style={{ background: COL.primary, animationDelay: '0s' }} />
                      <span className="w-0.5 h-3 rounded-full animate-pulse" style={{ background: COL.primary, animationDelay: '0.15s' }} />
                      <span className="w-0.5 h-3 rounded-full animate-pulse" style={{ background: COL.primary, animationDelay: '0.3s' }} />
                    </span>
                  )}
                </div>
              );
            })}
            {/* Live sub-label — shows current file/dir being read, AI thinking status, etc. */}
            {progressLabel && (
              <div className="flex items-center gap-2 pl-[5.5px] mt-0.5">
                <span className="w-px self-stretch" style={{ background: `${COL.primary}40` }} />
                <span className="text-[9px] truncate italic animate-pulse" style={{ color: '#8b949e', animationDuration: '2.5s' }}>
                  {progressLabel}
                </span>
              </div>
            )}
          </div>
        )}
        {features.length === 0 && !loading && (
          <div className="flex flex-col items-center justify-center py-8 gap-3">
            <button onClick={handleGenerate} className="text-caption px-3 py-1 rounded-full transition-colors hover:bg-white/10"
              style={{ border: `1px solid ${COL.outline}`, color: COL.primary }}>
              {tr(language, 'analyze')}
            </button>
          </div>
        )}
        {/* Recursive tree nodes */}
        {features.map((node) => (
          <TreeNode
            key={node.id}
            node={node}
            depth={0}
            expanded={expanded}
            selectedId={selectedId}
            onToggle={(id) => setExpanded((prev) => {
              const next = new Set(prev);
              next.has(id) ? next.delete(id) : next.add(id);
              return next;
            })}
            onSelect={onSelectFeature}
          />
        ))}
      </div>
    </div>
  );
}

/* ── Recursive tree node ── */
const LV_DOT: Record<number, string> = { 0: '#8b949e', 1: '#8ab4f8', 2: '#3fb950', 3: '#d29922' };

function TreeNode({ node, depth, expanded, selectedId, onToggle, onSelect }: {
  node: FeatureNode; depth: number; expanded: Set<string>; selectedId: string | null;
  onToggle: (id: string) => void; onSelect: (node: FeatureNode) => void;
}) {
  const hasChildren = node.children && node.children.length > 0;
  const isExpanded = expanded.has(node.id);
  const isSelected = selectedId === node.id;
  const padLeft = 12 + depth * 16;

  return (
    <div>
      <button
        onClick={() => {
          if (hasChildren) { onToggle(node.id); }
          onSelect(node);
        }}
        className={`w-full text-left py-1.5 border-b transition-colors hover:bg-white/[0.03] ${isSelected ? 'bg-white/[0.06]' : ''}`}
        style={{ paddingLeft: padLeft, paddingRight: 12, borderColor: '#30323440' }}>
        <div className="flex items-center gap-1.5">
          {/* Expand/collapse arrow */}
          {hasChildren && (
            <svg width="8" height="8" viewBox="0 0 24 24" fill="none" stroke="#5c6166" strokeWidth="2"
              style={{ transform: isExpanded ? 'rotate(90deg)' : 'rotate(0deg)', transition: 'transform 0.15s' }}>
              <path d="M9 18l6-6-6-6" />
            </svg>
          )}
          {!hasChildren && <span className="w-2 shrink-0" />}
          <div className="w-1.5 h-1.5 rounded-full shrink-0" style={{ background: LV_DOT[node.level] || '#8e918f' }} />
          <span className="text-xs font-medium truncate" style={{ color: 'var(--color-text-secondary)' }}>{node.label}</span>
          {node.children?.length > 0 && !isExpanded && (
            <span className="ml-auto text-[9px]" style={{ color: '#5c6166' }}>{node.children.length}</span>
          )}
        </div>
      </button>
      {/* Children */}
      {isExpanded && node.children?.map((child) => (
        <TreeNode
          key={child.id}
          node={child}
          depth={depth + 1}
          expanded={expanded}
          selectedId={selectedId}
          onToggle={onToggle}
          onSelect={onSelect}
        />
      ))}
    </div>
  );
}
